# Generated by Django 5.0.6 on 2024-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='default_username', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
