# Generated by Django 5.0.6 on 2024-07-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='default_username', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='default_password', max_length=150),
            preserve_default=False,
        ),
    ]
