# Generated by Django 5.0.6 on 2024-07-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_post_password_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
