# Generated by Django 5.0.6 on 2024-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_password_alter_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
